const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
(async () => {
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGP8z8DAwMDAxMDAwMDAAAANHQEDasKb6QAAAABJRU5ErkJggg==', 'base64');
  fs.mkdirSync(VAULT + '/attachments', { recursive: true }); fs.writeFileSync(VAULT + '/attachments/dune.png', png);
  w('Books/Dune.md', '---\ntags: [book, scifi]\nstatus: reading\nauthor: Herbert\npages: 700\nread: false\ncover: "[[dune.png]]"\n---\nSpice.');
  w('Books/Emma.md', '---\ntags:\n  - book\nstatus: done\nauthor: Austen\npages: 400\nread: true\n---\n');
  w('Books/Hobbit.md', '---\ntags: [book]\nstatus: todo\nauthor: Tolkien\npages: 300\nread: false\n---\n');
  w('Notes/Unrelated.md', 'nothing');
  w('Books.base', 'filters:\n  and:\n    - file.hasTag("book")\nviews:\n  - type: table\n    name: Table\n    order:\n      - file.name\n      - status\n      - author\n      - pages\n      - read\n');
  w('Reading.md', '# Reading\n\n```base\nfilters: status == "reading"\nviews:\n  - type: list\n    name: Now\n```\n\nBoard:\n\n![[Books.base#Board]]\n');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  const errors = []; global.PAGE = page; global.ERRS = errors;
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const cells = async () => page.$$eval('#view-base tbody tr', trs => trs.map(tr => [...tr.children].map(td => td.innerText.trim())));
  console.log('open a base');
  await page.keyboard.press('Control+o'); await page.keyboard.type('Books'); await page.keyboard.press('Enter'); await sleep(800);
  assert(await page.evaluate(() => S.view) === 'base', 'base view opens');
  let c = await cells();
  assert(c.length === 3 && c.map(r => r[0]).join() === 'Dune,Emma,Hobbit', 'three books, sorted by name: ' + c.map(r => r[0]));
  assert(c[0].join('|') === 'Dune|reading|Herbert|700|', 'cells show properties');
  assert((await page.textContent('#view-base tfoot')).includes('Σ 1400'), 'summary row sums numbers');
  console.log('sort, filter, columns (saved to the .base file)');
  await page.click('#view-base th[data-col=pages]'); await sleep(200);
  c = await cells();
  assert(c.map(r => r[0]).join() === 'Hobbit,Emma,Dune', 'header click sorts ascending');
  await page.click('#view-base th[data-col=pages]'); await sleep(1200);
  assert(/sort:\n\s+- property: pages\n\s+direction: DESC/.test(rd('Books.base')), 'sort saved to the .base file');
  await page.click('#view-base [data-act=filter]');
  await page.selectOption('#view-base [data-f=prop]', 'status');
  await page.selectOption('#view-base [data-f=op]', 'is not');
  await page.fill('#view-base [data-f=val]', 'done');
  await page.click('#view-base [data-act=add-filter]'); await sleep(200);
  c = await cells();
  assert(c.map(r => r[0]).join() === 'Dune,Hobbit', 'filter builder: status is not done');
  await page.fill('#view-base [data-f=expr]', 'file.mtime > now() - "1d" && pages >= 300');
  await page.click('#view-base [data-act=add-expr]'); await sleep(1200);
  assert((await cells()).length === 2 && rd('Books.base').includes('status != "done"') && rd('Books.base').includes('pages >= 300'), 'expression filters saved');
  await page.click('#view-base [data-act=rm-filter][data-i="0"]'); await page.click('#view-base [data-act=rm-filter][data-i="0"]'); await sleep(200);
  assert((await cells()).length === 3, 'filters removed');
  await page.click('#view-base [data-act=props]');
  await page.check('#view-base [data-prop="file.mtime"]'); await sleep(200);
  assert((await page.$$eval('#view-base th', t => t.map(x => x.textContent.trim()))).includes('Modified'), 'column picker adds file.mtime');
  await page.fill('#view-base [data-f=fname]', 'weeks'); await page.fill('#view-base [data-f=fexpr]', 'round(pages / 50 / 7, 1)');
  await page.click('#view-base [data-act=add-formula]'); await sleep(200);
  c = await cells();
  assert(c.find(r => r[0] === 'Dune').includes('2'), 'formula column computed (Dune: 700/50/7 = 2)');
  await page.keyboard.press('Escape'); await page.click('#view-base [data-act=props]'); await sleep(100);
  console.log('inline editing writes frontmatter');
  await page.dblclick('#view-base tr[data-row="Books/Hobbit.md"] td[data-col=status]');
  await page.keyboard.press('Control+a'); await page.keyboard.type('reading'); await page.keyboard.press('Enter'); await sleep(900);
  assert(rd('Books/Hobbit.md').includes('status: reading\n'), 'edited status saved to the note');
  await page.click('#view-base tr[data-row="Books/Hobbit.md"] td[data-col=read] input'); await sleep(900);
  assert(rd('Books/Hobbit.md').includes('read: true\n'), 'checkbox toggles a boolean property');
  assert(rd('Books/Hobbit.md').startsWith('---\ntags: [book]\nstatus: reading\nauthor: Tolkien\n'), 'other lines untouched');
  await page.fill('#view-base .bs-search', 'tolk'); await sleep(200);
  assert((await cells()).length === 1, 'search box filters rows');
  await page.fill('#view-base .bs-search', ''); await sleep(200);
  console.log('board and cards views');
  await page.click('#view-base [data-act=add-view]'); await page.click('#menu-root .menu div:has-text("Board view")'); await sleep(300);
  const cols = await page.$$eval('#view-base .bs-col[data-value] h4', h => h.map(x => x.textContent.trim()));
  assert(cols.join('|') === 'done 1|reading 2', 'board columns from status: ' + cols.join('|'));
  await page.evaluate(() => { const v = document.querySelector('#view-base [data-view="1"]'); v && v.click(); });
  await page.dragAndDrop('#view-base .bs-card[data-row="Books/Emma.md"]', '#view-base .bs-col[data-value="reading"]'); await sleep(900);
  assert(rd('Books/Emma.md').includes('status: reading\n'), 'dragging a card to a column changes the property');
  await page.screenshot({ path: OUT + '/50-board.png' });
  await page.click('#view-base [data-act=add-view]'); await page.click('#menu-root .menu div:has-text("Cards view")'); await sleep(200);
  await page.click('#view-base [data-act=view-menu]'); await page.click('#menu-root .menu div:has-text("Cover image")');
  await page.fill('.modal input', 'cover'); await page.keyboard.press('Enter'); await sleep(400);
  const cover = await page.$$eval('#view-base .bs-cover img', i => i.map(x => x.naturalWidth));
  assert(cover.length === 1 && cover[0] === 2, 'cards view shows the cover image from [[dune.png]]');
  await page.screenshot({ path: OUT + '/51-cards.png' });
  await sleep(1200);
  const saved = rd('Books.base');
  assert(saved.includes('type: board') && saved.includes('type: cards') && saved.includes('image: cover') && saved.includes('weeks:'), 'views and formula saved');
  console.log('new note from a view');
  await page.click('#view-base [data-view="1"]'); await sleep(200);
  await page.click('#view-base .bs-col[data-value="done"] [data-act=new-in]'); await sleep(700);
  const np = await page.evaluate(() => S.cur);
  assert(/^Untitled.*\.md$/.test(np) && rd(np) === '---\ntags:\n  - book\nstatus: done\n---\n', 'board "+ New" prefills tag and column value: ' + JSON.stringify(rd(np)));
  console.log('bases inside notes');
  await page.keyboard.press('Control+o'); await page.keyboard.type('Reading'); await page.keyboard.press('Enter'); await sleep(1200);
  const li = await page.$$eval('.cm-codeblock-widget .bs-list li', l => l.map(x => x.querySelector('.bs-name').textContent));
  assert(li.join() === 'Dune,Emma,Hobbit', '```base block renders live in the editor: ' + li);
  const boardCols = await page.$$eval('.cm-visual-embed .bs-col[data-value]', c => c.length);
  assert(boardCols >= 1, '![[Books.base#Board]] embed opens on the Board view');
  await page.screenshot({ path: OUT + '/52-note-embeds.png' });
  await page.click('.cm-codeblock-widget [data-act=sort]');
  await page.selectOption('.cm-codeblock-widget [data-f=sortprop]', 'pages');
  await page.click('.cm-codeblock-widget [data-act=add-sort]'); await sleep(1500);
  const note = rd('Reading.md');
  assert(/```base\nfilters: status == "reading"\nviews:\n  - type: list\n    name: Now\n    sort:\n      - property: pages\n        direction: ASC\n```/.test(note), 'view changes are written back into the code block: ' + JSON.stringify(note.slice(0, 160)));
  await page.keyboard.press('Control+e'); await sleep(500);
  assert(await page.$$eval('#preview .base-embed .bs-list li', l => l.length) === 3, 'reading view renders the block too');
  console.log('ERRORS:', errors.join('\n') || 'none');
  await browser.close();
})().catch(async e => { console.error(e.message); try { await global.PAGE.screenshot({ path: OUT + '/fail.png' }); } catch {} console.log('ERRORS:', (global.ERRS || []).join('\n')); process.exit(1); });
