const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
const ex = p => fs.existsSync(path.join(VAULT, p));
const pad = n => String(n).padStart(2, '0');
const day = k => { const d = new Date(); d.setDate(d.getDate() + k); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; };
(async () => {
  const Y = day(-1), T0 = day(0), TM = day(1);
  w(`Daily/${Y}.md`, '# yesterday\n' + 'words '.repeat(400));
  w('Work.md', `- [ ] Ship it 📅 ${TM}\n`);
  w('Templates/Daily.md', '# <% tp.date.now("dddd") %>\n');
  w('Templates/Weekly.md', 'Week of <% tp.date.weekday("YYYY-MM-DD", 0) %>\n');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 850 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  await page.evaluate(() => { cfg.dailyTemplate = 'Templates/Daily'; cfg.weeklyTemplate = 'Templates/Weekly'; saveCfg(); });
  await page.keyboard.press('Control+p'); await page.keyboard.type('show calendar'); await page.keyboard.press('Enter'); await sleep(300);
  assert(await page.$('#right-body .cal'), 'Show calendar opens the calendar tab');
  assert(await page.$(`.cal-day.today[data-day="${T0}"]`), 'today is marked');
  assert(await page.$$eval(`.cal-day[data-day="${Y}"] i b`, b => b.length) >= 2, 'a day with a longer note gets more dots');
  assert(await page.$(`.cal-day.due[data-day="${TM}"]`), 'a day with tasks due is ringed');
  await page.screenshot({ path: OUT + '/cal.png' });
  await page.click(`.cal-day[data-day="${TM}"]`); await sleep(700);
  const wd = new Date(); wd.setDate(wd.getDate() + 1);
  const name = wd.toLocaleDateString('en-US', { weekday: 'long' });
  assert(await page.evaluate(() => S.cur) === `Daily/${TM}.md` && rd(`Daily/${TM}.md`).startsWith(`# ${name}`), 'clicking a day makes its note, the template dated that day: ' + rd(`Daily/${TM}.md`).trim());
  assert(await page.$(`.cal-day.cur[data-day="${TM}"]`), 'and marks it as open');
  await page.click('.cal-row:not(.cal-names) .cal-wk >> nth=1'); await sleep(700);
  const cur = await page.evaluate(() => S.cur);
  assert(/^Daily\/\d{4}-W\d\d\.md$/.test(cur) && rd(cur).startsWith('Week of '), 'a week number makes the weekly note: ' + cur);
  await page.click('.cal-title'); await sleep(700);
  assert(await page.evaluate(() => S.cur) === `Daily/${T0.slice(0, 7)}.md`, 'the month’s name makes the monthly note');
  await page.click('[data-cal="1"]'); await sleep(200);
  const t1 = await page.textContent('.cal-title');
  await page.click('[data-cal="0"]'); await sleep(200);
  assert(t1 !== await page.textContent('.cal-title') && await page.$(`.cal-day.today`), 'the arrows change month, and Today comes back');
  await page.evaluate(tm => openPath(`Daily/${tm}.md`), TM); await sleep(300);
  await page.keyboard.press('Control+p'); await page.keyboard.type('previous daily note'); await page.keyboard.press('Enter'); await sleep(500);
  assert(await page.evaluate(() => S.cur) === `Daily/${Y}.md`, 'Previous daily note skips days without one');

  // A different name format.
  await page.evaluate(() => openSettings('daily')); await sleep(200);
  await page.fill('input[name=dailyFormat]', 'DD.MM.YYYY'); await sleep(900);
  const pv = await page.textContent('.st-pp');
  assert(pv.includes(`Daily/${T0.slice(8)}.${T0.slice(5, 7)}.${T0.slice(0, 4)}.md`), 'Settings shows what today’s note would be called: ' + pv);
  await page.click('.st [data-x]'); await sleep(100);
  await page.click('[data-cmd=daily]'); await sleep(700);
  assert(await page.evaluate(() => S.cur) === `Daily/${T0.slice(8)}.${T0.slice(5, 7)}.${T0.slice(0, 4)}.md`, 'and the daily note uses it');
  assert(await page.$(`.cal-day.cur[data-day="${T0}"]`), 'the calendar recognises the new format');
  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
