const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
(async () => {
  w('Plan.md', '# Plan\n\nSome text\n');
  w('Other.md', '# Other\n');
  w('Board.canvas', JSON.stringify({ nodes: [
    { id: 'n1', type: 'file', file: 'Plan.md', x: 0, y: 0, width: 400, height: 260 },
    { id: 't1', type: 'text', text: 'Hello card', x: 500, y: 0, width: 300, height: 120 },
  ], edges: [] }, null, '\t'));
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(800);
  await page.keyboard.press('Control+o'); await page.keyboard.type('Board'); await page.keyboard.press('Enter'); await sleep(900);
  console.log('note card edits the note in place');
  await page.click('.cv-node[data-id=n1] .cv-content'); await sleep(100);
  await page.keyboard.press('Enter'); await sleep(300);
  assert(await page.$('.cv-node[data-id=n1] .cv-cm .cm-content'), 'Enter opens an editor inside the note card');
  assert(await page.evaluate(() => document.activeElement.closest('.cv-cm') !== null), 'the card editor has focus');
  assert(await page.evaluate(() => S.view === 'canvas'), 'still on the canvas');
  await page.keyboard.press('Control+End');
  await page.keyboard.type('Added from canvas $x^2$ ');
  await sleep(1500);
  assert(rd('Plan.md').includes('Added from canvas $x^2$'), 'typing saves the note: ' + JSON.stringify(rd('Plan.md')));
  const before = await page.evaluate(() => CinderCanvas.getView());
  await page.mouse.move(150, 200); await page.mouse.wheel(0, 300); await sleep(200);
  const after = await page.evaluate(() => CinderCanvas.getView());
  assert(before.x === after.x && before.y === after.y, 'wheeling inside the editor does not pan the canvas');
  await page.keyboard.press('Escape'); await sleep(300);
  assert(!(await page.$('.cv-cm')), 'Esc closes the card editor');
  assert(await page.$eval('.cv-node[data-id=n1] .cv-content', c => c.textContent.includes('Added from canvas') && !!c.querySelector('.katex')), 'the card shows the new text with rendered math');
  assert(await page.evaluate(() => document.activeElement.classList.contains('cv-viewport')), 'focus returns to the canvas');
  console.log('text card uses the live editor');
  await page.dblclick('.cv-node[data-id=t1] .cv-content'); await sleep(300);
  assert(await page.$('.cv-node[data-id=t1] .cv-cm .cm-content'), 'double-click opens the live editor in a text card');
  await page.keyboard.type(' and [[Oth'); await sleep(400);
  assert(await page.$('.cm-tooltip-autocomplete'), 'link autocomplete appears');
  await page.keyboard.press('Escape'); await sleep(150);
  assert(await page.$('.cv-cm') && !(await page.$('.cm-tooltip-autocomplete')), 'first Esc closes only the popup');
  await page.keyboard.press('Escape'); await sleep(1500);
  assert(!(await page.$('.cv-cm')), 'second Esc finishes editing');
  const d = JSON.parse(rd('Board.canvas'));
  assert(d.nodes.find(n => n.id === 't1').text === 'Hello card and [[Oth]]', 'text card saved: ' + JSON.stringify(d.nodes.find(n => n.id === 't1').text));
  console.log('Tab still makes a connected card');
  await page.click('.cv-node[data-id=t1] .cv-content'); await page.keyboard.press('Enter'); await sleep(200);
  await page.keyboard.press('Tab'); await sleep(300);
  await page.keyboard.type('Child'); await page.keyboard.press('Escape'); await sleep(1500);
  const d2 = JSON.parse(rd('Board.canvas'));
  assert(d2.nodes.some(n => n.text === 'Child') && d2.edges.length === 1, 'Tab made a connected child card');
  console.log('Vim mode: Esc leaves insert mode first');
  await page.evaluate(() => { cfg.vim = true; });
  await page.click('.cv-node[data-id=t1] .cv-content'); await page.keyboard.press('Enter'); await sleep(300);
  await page.keyboard.press('A'); await page.keyboard.type('!'); await page.keyboard.press('Escape'); await sleep(150);
  assert(await page.$('.cv-cm'), 'Esc in insert mode stays in the editor');
  await page.keyboard.press('Escape'); await sleep(300);
  assert(!(await page.$('.cv-cm')), 'Esc in normal mode finishes');
  await page.evaluate(() => { cfg.vim = false; });
  await sleep(1300);
  assert(JSON.parse(rd('Board.canvas')).nodes.find(n => n.id === 't1').text.endsWith('!'), 'vim edit saved');
  console.log('Shift+Enter opens the note');
  await page.click('[data-act=fit]'); await sleep(200);
  await page.click('.cv-node[data-id=n1] .cv-content'); await page.keyboard.press('Shift+Enter'); await sleep(700);
  assert(await page.evaluate(() => S.cur === 'Plan.md' && S.view === 'note'), 'Shift+Enter opens the note page');
  assert(await page.evaluate(() => ed.value.includes('Added from canvas')), 'the note page shows the canvas edit');
  if (errors.length) { console.log(errors.join('\n')); process.exitCode = 1; }
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
