const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const WEB = 'http://127.0.0.1:43200/page.html';
(async () => {
  w('Web.md', `# Web\n\n![|600x300](${WEB})\n\ntext after\n`);
  w('Links.md', `# Links\n\nSee [[Other]] and ${WEB} here.\n\nAlso [site](${WEB}).\n`);
  w('Other.md', '# Other\n\nThe other note, previewed.\n\n## Part\npart text\n');
  w('Board.canvas', JSON.stringify({ nodes: [{ id: 'l1', type: 'link', url: WEB, x: 0, y: 0, width: 400, height: 300 }], edges: [] }));
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error' && !/favicon/.test(m.text())) errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const open = async q => { await page.keyboard.press('Control+o'); await page.keyboard.type(q); await page.keyboard.press('Enter'); await sleep(800); };
  const webFrame = () => page.frames().find(f => f.url() === WEB);

  console.log('web page embeds');
  await open('Web');
  await page.evaluate(() => setMode('edit')); await sleep(800);
  assert(await page.$('#editor .cm-web-embed iframe[sandbox]'), '![](https://…) shows a sandboxed frame in live preview');
  assert(await page.$eval('#editor .cm-web-embed .we-frame', f => f.getBoundingClientRect().height) === 300, '|600x300 sizes it');
  await page.waitForFunction(u => [...document.querySelectorAll('iframe')].some(f => f.src === u), WEB); await sleep(600);
  assert(await webFrame()?.$eval('#hi', h => h.textContent).catch(() => null) === 'Hello from the web', 'and the live page loads in it');
  await page.evaluate(() => setMode('read')); await sleep(500);
  assert(await page.$('#preview .web-embed iframe'), 'reading view embeds it too');
  assert(await page.evaluate(() => framedUrl('https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=5') === 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ' && framedUrl('https://youtu.be/dQw4w9WgXcQ').endsWith('/embed/dQw4w9WgXcQ')), 'YouTube links become the player');
  await page.evaluate(() => { cfg.webEmbeds = 'click'; renderPreview(); }); await sleep(300);
  assert(await page.$('#preview .web-embed .we-ask button') && !(await page.$('#preview .web-embed iframe')), '"Load when clicked" asks first');
  await page.click('#preview .web-embed .we-ask button'); await sleep(300);
  assert(await page.$('#preview .web-embed iframe'), 'and loads on click');
  await page.evaluate(() => { cfg.webEmbeds = 'auto'; });

  console.log('resizing');
  await page.evaluate(() => setMode('edit')); await sleep(600);
  const srcBefore = await page.$('#editor .cm-web-embed iframe');
  const g = await page.locator('#editor .cm-web-embed .we-grip').boundingBox();
  await page.mouse.move(g.x + 8, g.y + 8); await page.mouse.down(); await page.mouse.move(g.x - 92, g.y + 108, { steps: 6 }); await page.mouse.up(); await sleep(300);
  const v = await page.evaluate(() => ed.value);
  const m = /!\[\|(\d+)x(\d+)\]\(http:\/\/127\.0\.0\.1:43200\/page\.html\)/.exec(v);
  assert(m && Math.abs(+m[2] - 400) < 4 && Math.abs(+m[1] - 500) < 6, 'dragging the corner writes the new size into the note: ' + (m && m[0]));
  assert(await page.$eval('#editor .cm-web-embed .we-frame', f => Math.round(f.getBoundingClientRect().height)) === +m[2], 'and the page shows at that size');
  assert(await page.evaluate(old => document.querySelector('#editor .cm-web-embed iframe') === old && old.isConnected, srcBefore), 'without reloading it (same frame)');
  await page.dblclick('#editor .cm-web-embed .we-grip'); await sleep(300);
  assert((await page.evaluate(() => ed.value)).includes('![](http://127.0.0.1:43200/page.html)'), 'double-clicking the grip goes back to the default size');
  await page.evaluate(() => setMode('read')); await sleep(500);
  const g2 = await page.locator('#preview .web-embed .we-grip').boundingBox();
  await page.mouse.move(g2.x + 8, g2.y + 8); await page.mouse.down(); await page.mouse.move(g2.x + 8, g2.y - 150, { steps: 5 }); await page.mouse.up(); await sleep(300);
  assert(/!\[\|x3\d\d\]\(http/.test(await page.evaluate(() => ed.value)), 'resizing works in reading view too (height only at full width): ' + (await page.evaluate(() => ed.value)).split('\n')[2]);

  console.log('embed and un-embed links');
  await open('Links');
  await page.evaluate(() => setMode('edit')); await sleep(400);
  await page.evaluate(() => ed.setSelectionRange(ed.value.length)); await sleep(200);
  await page.click('#editor .cm-wikilink[data-link="Other"]', { button: 'right' }); await sleep(150);
  await page.click('.menu >> text=Embed (show it here)'); await sleep(400);
  assert((await page.evaluate(() => ed.value)).includes('See ![[Other]] and'), 'Embed turns [[Other]] into ![[Other]]');
  await page.evaluate(() => { const i = ed.value.indexOf('http'); ed.setSelectionRange(i + 3); toggleEmbed(ed, i + 3); }); await sleep(200);
  assert((await page.evaluate(() => ed.value)).includes(`![](${'http://127.0.0.1:43200/page.html'})`), 'a bare address becomes ![](address)');
  await page.evaluate(() => { const i = ed.value.indexOf('![]('); toggleEmbed(ed, i + 2); }); await sleep(200);
  assert((await page.evaluate(() => ed.value)).includes(' http://127.0.0.1:43200/page.html here'), 'and back to the bare address');
  await page.evaluate(() => { ed.value = '![[Other]]\n\nend\n'; ed.setSelectionRange(ed.value.length); }); await sleep(500);
  await page.click('#editor .cm-note-embed', { button: 'right' }); await sleep(150);
  await page.click('.menu >> text=Show as a link'); await sleep(300);
  assert((await page.evaluate(() => ed.value)).startsWith('[[Other]]'), 'right-click an embed: Show as a link');

  console.log('hover previews');
  await page.evaluate(() => { ed.value = `See [[Other#Part]] and [site](${'http://127.0.0.1:43200/page.html'}).\n`; setMode('read'); }); await sleep(400);
  await page.hover('#preview a.internal-link'); await sleep(800);
  assert(await page.$eval('.hover-pop .hp-body', b => b.textContent.includes('part text') && !b.textContent.includes('previewed')), 'hovering a note link previews it (just the #section)');
  await page.mouse.move(5, 500); await sleep(600);
  assert(!(await page.$('.hover-pop')), 'moving away closes it');
  await page.hover('#preview a[href^="http"]'); await sleep(700);
  assert(!(await page.$('.hover-pop')), 'web links need Ctrl');
  await page.keyboard.down('Control'); await sleep(500); await page.keyboard.up('Control');
  assert(await page.$('.hover-pop.hp-web iframe'), 'Ctrl while hovering a web link shows the live page');
  await page.keyboard.press('Escape'); await sleep(100);
  assert(!(await page.$('.hover-pop')), 'Esc closes it');
  await page.evaluate(() => setMode('edit')); await sleep(400);
  await page.hover('#editor .cm-wikilink'); await sleep(700);
  assert(!(await page.$('.hover-pop')), 'in the editor a plain hover does nothing');
  await page.keyboard.down('Control'); await sleep(400); await page.keyboard.up('Control');
  assert(await page.$('.hover-pop .hp-body'), 'Ctrl+hover previews in the editor');
  await page.keyboard.press('Escape');

  console.log('nested previews');
  await page.evaluate(() => { ed.value = 'See [[Other]] here.\n'; setMode('read'); }); await sleep(300);
  await page.evaluate(() => { const n = S.notes.get('Other.md'); }); 
  fs.writeFileSync(path.join(VAULT, 'Other.md'), '# Other\n\nThe other note, previewed. Also [[Third]].\n\n## Part\npart text\n');
  fs.writeFileSync(path.join(VAULT, 'Third.md'), '# Third\n\nThird note.\n');
  await page.evaluate(() => loadAll()); await sleep(600);
  await page.evaluate(() => renderPreview()); await sleep(200);
  await page.hover('#preview a.internal-link'); await sleep(800);
  await page.hover('.hover-pop a.internal-link'); await sleep(900);
  const stack = await page.$$eval('.hover-pop .hp-head b', b => b.map(x => x.textContent));
  assert(JSON.stringify(stack) === '["Other","Third"]', 'a link inside a preview opens another preview on top: ' + JSON.stringify(stack));
  const [p1, p2] = await page.$$eval('.hover-pop', ps => ps.map(p => p.getBoundingClientRect().toJSON()));
  assert(p2.left > 20 && p2.top > 20, 'placed by its link, not in the corner');
  await page.keyboard.press('Escape'); await sleep(100);
  assert(await page.$$eval('.hover-pop', p => p.length) === 1, 'Esc closes just the top one');
  await page.hover('.hover-pop a.internal-link'); await sleep(900);
  await page.hover('.hover-pop .hp-body'); await sleep(600);
  assert(await page.$$eval('.hover-pop', p => p.length) === 1, 'moving back into the first closes the second');
  await page.mouse.move(5, 500); await sleep(600);
  assert(await page.$$eval('.hover-pop', p => p.length) === 0, 'and leaving them all closes everything');

  console.log('canvas link cards');
  await open('Board'); await sleep(800);
  assert(await page.$('.cv-node[data-id=l1] .cv-web iframe'), 'a link card shows the live page');
  assert(await page.$eval('.cv-node[data-id=l1] .cv-web iframe', f => getComputedStyle(f).pointerEvents === 'none'), 'unselected, the card drags instead of the page taking the pointer');
  await page.click('.cv-node[data-id=l1] .we-bar'); await sleep(150);
  assert(await page.$eval('.cv-node[data-id=l1] .cv-web iframe', f => getComputedStyle(f).pointerEvents !== 'none'), 'selected, the page is usable');

  if (errors.length) { console.log(errors.join('\n')); process.exitCode = 1; }
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
