const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
(async () => {
  w('Daily.md', '# Today\n\n- [ ] call Sam\n- [ ] email Jo\n\n```tasks\nnot done\npath includes Daily\n```\n');
  w('Books/Dune.md', '---\nstatus: reading\nread: false\n---\n');
  w('Books/Emma.md', '---\nstatus: done\nread: true\n---\n');
  w('Books.base', 'filters: file.inFolder("Books")\nviews:\n  - type: table\n    name: Table\n  - type: board\n    name: Board\n    groupBy:\n      property: status\n  - type: cards\n    name: Cards\n    order: [file.name, read]\n');
  w('Shelf.md', '# Shelf\n\n![[Books.base]]\n\n~~~Base\nfilters: file.inFolder("Books")\nviews:\n  - type: table\n    name: T\n~~~\n');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 900 } });
  const errors = []; global.PAGE = page;
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(800);
  const open = async q => { await page.keyboard.press('Control+o'); await page.keyboard.type(q); await page.keyboard.press('Enter'); await sleep(900); };
  console.log('tasks block in the open note');
  await open('Daily');
  await page.evaluate(() => { if (S.mode !== 'edit') setMode('edit'); ed.setSelectionRange(0, 0); });
  await sleep(300);
  await page.click('.cm-codeblock-widget .tk-row:has-text("call Sam") .tk-check'); await sleep(1100);
  assert(await page.evaluate(() => /- \[x\] call Sam/.test(ed.value)), 'first tick lands in the editor');
  assert(!(await page.$('.cm-codeblock-widget .tk-row:has-text("call Sam")')), 'the block redraws without the done task');
  await page.click('.cm-codeblock-widget .tk-row:has-text("email Jo") .tk-check'); await sleep(1100);
  assert(await page.evaluate(() => /- \[x\] email Jo/.test(ed.value)), 'a second tick works too (no "task has changed" error)');
  console.log('embedded base keeps its view; cards checkbox; ~~~Base block');
  await open('Shelf');
  await page.evaluate(() => { if (S.mode !== 'edit') setMode('edit'); ed.setSelectionRange(0, 0); });
  await sleep(400);
  const emb = '.cm-visual-embed.base-embed';
  await page.click(`${emb} [data-view="1"]`); await sleep(200);
  await page.dragAndDrop(`${emb} .bs-card[data-row="Books/Dune.md"]`, `${emb} .bs-col[data-value="done"]`); await sleep(1200);
  assert(rd('Books/Dune.md').includes('status: done'), 'dragging a card in an embedded board saves');
  assert(await page.$eval(`${emb} .bs-tab.on`, t => t.textContent.trim()) === 'Board', 'the embed stays on the Board view after the edit');
  await page.click(`${emb} [data-view="2"]`); await sleep(200);
  await page.click(`${emb} .bs-card[data-row="Books/Dune.md"] .bs-check`); await sleep(1200);
  assert(rd('Books/Dune.md').includes('read: true'), 'ticking a checkbox in cards view saves the property');
  const blk = '.cm-codeblock-widget .base-embed';
  await page.click(`${blk} th[data-col="file.name"]`); await sleep(300); await page.click(`${blk} th[data-col="file.name"]`); await sleep(1200);
  assert(/~~~Base\n[\s\S]*sort:\n\s+- property: file.name\n\s+direction: DESC\n~~~/.test(rd('Shelf.md')), 'a ~~~Base block saves its view changes: ' + JSON.stringify(rd('Shelf.md').slice(-120)));
  console.log('cell editor closes on an unchanged value');
  await open('Books.base');
  await page.dblclick('#view-base tr[data-row="Books/Emma.md"] td[data-col=status]'); await sleep(100);
  await page.keyboard.press('Enter'); await sleep(500);
  assert(!(await page.$('#view-base .bs-cell-edit')), 'no editor left in the cell');
  console.log('drawings: undo after deleting an image keeps its data');
  await page.click('[data-cmd=new-drawing]'); await sleep(600);
  const dpath = await page.evaluate(() => S.cur);
  await page.evaluate(async () => {
    const c = document.createElement('canvas'); c.width = 20; c.height = 20; c.getContext('2d').fillRect(0, 0, 20, 20);
    const blob = await new Promise(r => c.toBlob(r)); const f = new File([blob], 'x.png', { type: 'image/png' });
    const dt = new DataTransfer(); dt.items.add(f);
    document.querySelector('.dr-canvas').dispatchEvent(new DragEvent('drop', { dataTransfer: dt, clientX: 700, clientY: 400, bubbles: true }));
  });
  await sleep(600);
  await page.keyboard.press('Delete'); await sleep(1200); // autosave runs with the image gone
  await page.keyboard.press('Control+z'); await sleep(1500);
  const d = JSON.parse(rd(dpath));
  const img = d.elements.find(e => e.type === 'image');
  assert(img && d.files[img.fileId]?.dataURL?.startsWith('data:image/png'), 'the restored image still has its data on disk');
  console.log('board with many cards in one column');
  for (let i = 0; i < 25; i++) w(`Many/M${i}.md`, `note ${i}\n`);
  w('Crowd.base', 'filters: file.inFolder("Many")\nviews:\n  - type: board\n    name: Board\n    groupBy:\n      property: status\n');
  await page.evaluate(() => loadAll()); await sleep(800);
  await open('Crowd.base'); await sleep(500);
  const hs = await page.$$eval('#view-base .bs-colbody .bs-card', c => c.map(x => x.getBoundingClientRect().height));
  assert(hs.length === 25 && Math.min(...hs) > 30, 'cards keep their height instead of squashing (min ' + Math.min(...hs).toFixed(1) + 'px)');
  assert(await page.$eval('#view-base .bs-colbody', b => b.scrollHeight > b.clientHeight + 10), 'the column scrolls');
  assert(await page.$('#view-base .bs-hint'), 'a hint explains that no note has the property yet');
  console.log('ERRORS:', errors.join('\n') || 'none');
  await browser.close();
})().catch(async e => { console.error(e.message); try { await global.PAGE.screenshot({ path: OUT + '/fail.png' }); } catch {} process.exit(1); });
