const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
(async () => {
  fs.writeFileSync(VAULT + '/Icons.md', '# Icons \n\nInline `code ` and text.\n\n```rust\nfn main() {} // \n```\n');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  const errors = []; global.PAGE = page;
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(800);
  await page.keyboard.press('Control+o'); await page.keyboard.type('Icons'); await page.keyboard.press('Enter'); await sleep(900);
  const faces = await page.evaluate(async () => { await document.fonts.ready; return [...document.fonts].filter(f => f.status === 'loaded').map(f => `${f.family}/${f.weight}/${f.style}`); });
  assert(faces.some(f => f.includes('Symbols Nerd Font Mono')), 'Nerd symbols font loads when a page has icons: ' + faces.join(', '));
  assert(faces.some(f => f.includes('JetBrains Mono')), 'JetBrains Mono loads for code');
  const codeFont = await page.$eval('.cm-line.cm-codeblock', el => getComputedStyle(el).fontFamily);
  assert(codeFont.startsWith('"JetBrains Mono"') && codeFont.endsWith('"Symbols Nerd Font Mono"'), 'code blocks use JetBrains Mono with the symbols fallback');
  // The icon glyph really comes from the symbols font: measure it vs. a missing-glyph box.
  const w = await page.evaluate(() => { const c = document.createElement('canvas').getContext('2d'); c.font = '40px "Symbols Nerd Font Mono"'; const a = c.measureText('').width; c.font = '40px serif'; const b = c.measureText('').width; return [a, b]; });
  assert(w[0] > 20, 'icon has a real glyph (width ' + w.map(x => x.toFixed(1)) + ')');
  // text before the icon font can't come from it
  const latin = await page.evaluate(() => document.fonts.check('16px "Symbols Nerd Font Mono"', 'abc'));
  console.log('    (symbols font covers latin text:', latin, ')');
  console.log('settings');
  await page.evaluate(() => openSettings('appearance'));
  await page.fill('input[name=fontText]', 'Georgia');
  await page.fill('input[name=fontMono]', 'Fira Code');
  assert((await page.$eval('.fp-mono', el => el.style.fontFamily)).startsWith('"Fira Code"'), 'preview follows the typed font');
  await page.screenshot({ path: OUT + '/70-font-settings.png' });
  await page.keyboard.press('Tab'); await page.click('.st [data-x]'); await sleep(300);
  const ef = await page.$eval('#editor .cm-editor', el => getComputedStyle(el).fontFamily);
  assert(/^"?Georgia"?,/.test(ef) && ef.includes('Symbols Nerd Font Mono'), 'editor text font: ' + ef);
  const cf = await page.$eval('.cm-line.cm-codeblock', el => getComputedStyle(el).fontFamily);
  assert(cf.startsWith('"Fira Code", "JetBrains Mono"'), 'code font puts the choice first, JetBrains Mono behind it');
  await page.evaluate(() => openSettings('appearance')); await page.fill('input[name=fontText]', 'x"; } body { color: red'); await page.keyboard.press('Tab'); await page.click('.st [data-x]'); await sleep(200);
  const inj = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--font-text'));
  assert(!/[;{}]/.test(inj), 'font names can\'t inject CSS: ' + inj);
  await page.evaluate(() => openSettings('appearance')); await page.fill('input[name=fontText]', ''); await page.fill('input[name=fontMono]', ''); await page.keyboard.press('Tab'); await page.click('.st [data-x]'); await sleep(200);
  console.log('icon picker');
  await page.evaluate(() => { ed.setSelectionRange(ed.value.length, ed.value.length); });
  await page.keyboard.press('Control+p'); await page.keyboard.type('Insert icon'); await page.keyboard.press('Enter'); await sleep(500);
  await page.keyboard.type('github'); await sleep(200);
  const first = await page.$$eval('.pick .main', p => p.slice(0, 3).map(x => x.textContent));
  assert(first.length && first.every(x => /github/i.test(x)), 'search finds github icons: ' + first.join(' | '));
  await page.screenshot({ path: OUT + '/71-icon-picker.png' });
  await page.keyboard.press('Enter'); await sleep(900);
  const content = fs.readFileSync(VAULT + '/Icons.md', 'utf8');
  assert(/[-]|[\uDB80-\uDBFF][\uDC00-\uDFFF]/.test(content.slice(-3)), 'the icon was inserted into the note');
  const md = await page.evaluate(async () => { const l = await loadNerdIcons(); return [l.length, l.find(x => x.full === 'md-calendar')?.char.codePointAt(0).toString(16)]; });
  assert(md[0] > 10000 && md[1] === 'f00ed', 'material icons in the supplementary private-use area parse (' + md + ')');
  await page.keyboard.press('Control+e'); await sleep(400);
  await page.screenshot({ path: OUT + '/72-icons-note.png' });
  console.log('ERRORS:', errors.join('\n') || 'none');
  await browser.close();
})().catch(async e => { console.error(e.message); try { await global.PAGE.screenshot({ path: OUT + '/fail.png' }); } catch {} process.exit(1); });
