const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
const pad = n => String(n).padStart(2, '0');
const d = new Date(), TODAY = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
(async () => {
  w('Notes/Alpha.md', '# Alpha\nhello world\n');
  w('Notes/Beta.md', '# Beta\n');
  w('Zeta.md', '# Zeta\nhello again\n');
  w('Todo.md', `- [ ] first 📅 ${TODAY}\n- [ ] second 📅 ${TODAY}\n- [ ] third 📅 ${TODAY}\n`);
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const active = () => page.evaluate(() => { const a = document.activeElement; return a.id || a.className || a.tagName; });
  const kb = () => page.evaluate(() => document.querySelector('#tree .t-row.kb .name')?.textContent);

  console.log('file tree');
  await page.keyboard.press('Control+Shift+E'); await sleep(200);
  assert(await active() === 'tree', 'Ctrl+Shift+E focuses the file tree');
  await page.keyboard.press('Home'); await sleep(50);
  assert(await kb() === 'Notes', 'Home goes to the first row (a folder)');
  await page.keyboard.press('ArrowRight'); await sleep(150);
  assert(await page.$('#tree .t-row[data-path="Notes/Alpha.md"]'), '→ expands the folder');
  await page.keyboard.press('ArrowDown'); await sleep(50);
  assert(await kb() === 'Alpha', '↓ moves into it');
  await page.keyboard.press('ArrowLeft'); await sleep(50);
  assert(await kb() === 'Notes', '← on a file goes to its folder');
  await page.keyboard.press('ArrowLeft'); await sleep(150);
  assert(!(await page.$('#tree .t-row[data-path="Notes/Alpha.md"]')), '← on an open folder collapses it');
  await page.keyboard.press('ArrowRight'); await sleep(150); await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter'); await sleep(700);
  assert(await page.evaluate(() => S.cur === 'Notes/Alpha.md'), 'Enter opens the note');
  assert(/cm-content/.test(await active()), 'and puts the cursor in the editor');
  await page.keyboard.press('Control+Shift+E'); await sleep(150);
  assert(await kb() === 'Alpha', 'the tree remembers where it was');
  await page.keyboard.type('ze'); await sleep(50);
  assert(await kb() === 'Zeta', 'typing a name jumps to it');
  await page.keyboard.press('Space'); await sleep(600);
  assert(await page.evaluate(() => S.cur === 'Zeta.md') && await active() === 'tree', 'Space opens it but stays in the tree');
  await page.keyboard.press('F2'); await sleep(200);
  assert(await page.$('#modal-root .modal input'), 'F2 renames the row');
  await page.keyboard.press('Escape'); await sleep(150);
  await page.keyboard.press('Escape'); await sleep(150);
  assert(/cm-content|preview/.test(await active()), 'Esc goes back to the page');

  console.log('shortcuts sheet and sidebars');
  await page.keyboard.press('Control+/'); await sleep(200);
  assert(await page.$eval('#modal-root', m => m.textContent.includes('Keyboard shortcuts') && m.textContent.includes('Heading 2')), 'Ctrl+/ shows the shortcuts, even from the editor');
  await page.keyboard.press('Escape'); await sleep(150);
  assert(!(await page.$('#modal-root .modal')), 'Esc closes it');
  await page.keyboard.press('Control+\\'); await sleep(100);
  assert(await page.evaluate(() => document.body.classList.contains('app-no-left')), 'Ctrl+\\ hides the left sidebar');
  await page.keyboard.press('Control+Shift+Backslash'); await sleep(100);
  assert(await page.evaluate(() => document.body.classList.contains('app-no-right')), 'Ctrl+Shift+\\ hides the right one');
  await page.keyboard.press('Control+Shift+Backslash'); await sleep(100);
  await page.keyboard.press('Control+Shift+E'); await sleep(150);
  assert(await page.evaluate(() => !document.body.classList.contains('app-no-left')), 'focusing the tree brings the sidebar back');
  await page.keyboard.press('Escape');

  console.log('editor commands');
  await page.evaluate(() => { openPath('Zeta.md'); });
  await sleep(500);
  await page.evaluate(() => { setMode('edit'); ed.setSelectionRange(ed.value.indexOf('hello')); ed.focus(); });
  await page.keyboard.press('Control+2'); await sleep(100);
  assert((await page.evaluate(() => ed.value)).includes('## hello again'), 'Ctrl+2 makes a heading');
  await page.keyboard.press('Control+2'); await sleep(100);
  assert((await page.evaluate(() => ed.value)).includes('\nhello again'), 'again removes it');
  await page.keyboard.press('Control+Shift+8'); await sleep(100);
  assert((await page.evaluate(() => ed.value)).includes('- hello again'), 'Ctrl+Shift+8 makes a bullet');
  await page.keyboard.press('Control+Shift+9'); await sleep(100);
  assert((await page.evaluate(() => ed.value)).includes('- [ ] hello again'), 'Ctrl+Shift+9 turns it into a task');

  console.log('rebinding');
  await page.keyboard.press('Control+p'); await page.keyboard.type('customize hotkeys'); await page.keyboard.press('Enter'); await sleep(250);
  await page.fill('.hk-q', 'graph view'); await sleep(100);
  await page.click('.hk-row[data-id="graph"] [data-rec]'); await sleep(50);
  await page.keyboard.press('Alt+g'); await sleep(100);
  assert(await page.evaluate(() => cfg.hotkeys.graph === 'Alt-g'), 'recording a key saves it');
  assert(await page.$eval('.hk-row[data-id="graph"] .hk-key', b => b.textContent === 'Alt+G'), 'and shows it');
  await page.fill('.hk-q', 'bold'); await sleep(100);
  await page.click('.hk-row[data-id="editor:bold"] [data-rec]'); await page.keyboard.press('Control+i'); await sleep(100);
  assert(await page.$('.hk-row[data-id="editor:bold"].clash'), 'a clash with Italic is flagged');
  await page.click('.hk-row[data-id="editor:bold"] [data-rec]'); await page.keyboard.press('Alt+b'); await sleep(100);
  assert(!(await page.$('.hk-row[data-id="editor:bold"].clash')), 'rebinding clears it');
  await page.keyboard.press('Escape'); await sleep(150);
  assert(!(await page.$('#modal-root .modal')), 'Esc closes the hotkeys screen');
  await page.evaluate(() => { ed.setSelectionRange(ed.value.indexOf('again'), ed.value.indexOf('again') + 5); ed.focus(); });
  await page.keyboard.press('Alt+b'); await sleep(100);
  assert((await page.evaluate(() => ed.value)).includes('**again**'), 'the new editor key works');
  await page.keyboard.press('Control+b'); await sleep(100);
  assert(!(await page.evaluate(() => ed.value)).includes('****'), 'the old one is gone');
  await page.keyboard.press('Control+g'); await sleep(300);
  assert(await page.evaluate(() => S.view === 'note'), 'Ctrl+G no longer opens the graph');
  await page.keyboard.press('Alt+g'); await sleep(400);
  assert(await page.evaluate(() => S.view === 'graph'), 'Alt+G does');
  const stored = await page.evaluate(() => JSON.stringify(cfg.hotkeys));
  await page.reload(); await sleep(1000);
  assert(await page.evaluate(() => JSON.stringify(cfg.hotkeys)) === stored && await page.evaluate(() => HOTKEYS.get('Alt-g')?.id === 'graph'), 'bindings survive a reload');
  assert((await page.$eval('[data-cmd=graph]', b => b.title)).includes('Alt+G'), 'button tooltips show the new key');

  console.log('palette remembers');
  await page.keyboard.press('Control+p'); await sleep(150);
  assert(await page.$eval('.pick.sel .main', e => e.textContent) === 'Customize hotkeys…', 'the last command used comes first');
  await page.keyboard.press('Escape');

  console.log('search results');
  await page.keyboard.press('Control+Shift+F'); await page.keyboard.type('hello'); await sleep(500);
  await page.keyboard.press('ArrowDown'); await sleep(50);
  assert(await page.evaluate(() => document.activeElement.classList.contains('s-file-name')), '↓ from the search box moves into the results');
  await page.keyboard.press('ArrowDown'); await sleep(50);
  assert(await page.evaluate(() => document.activeElement.classList.contains('s-snip')), '↓ again reaches a match');
  await page.keyboard.press('Enter'); await sleep(600);
  assert(await page.evaluate(() => /hello/.test(ed.value.slice(ed.selectionStart, ed.selectionEnd))), 'Enter opens the note at the match');

  console.log('tasks');
  await page.keyboard.press('Control+Shift+T'); await sleep(600);
  await page.keyboard.press('ArrowDown'); await sleep(50);
  assert(await page.evaluate(() => document.activeElement.classList.contains('tk-row')), '↓ from the add box focuses the first task');
  await page.keyboard.press('j'); await sleep(50);
  const second = await page.evaluate(() => document.activeElement.textContent);
  assert(/second/.test(second), 'j moves down');
  await page.keyboard.press('x'); await sleep(900);
  assert(/- \[x\] second/.test(rd('Todo.md')), 'x ticks it');
  assert(await page.evaluate(() => document.activeElement.classList.contains('tk-row')), 'focus stays in the list after it redraws');
  const now = await page.evaluate(() => document.activeElement.textContent);
  await page.keyboard.press('m'); await sleep(900);
  const which = /third/.test(now) ? 'third' : 'first';
  const tm = new Date(Date.now() + 864e5), TOM = `${tm.getFullYear()}-${pad(tm.getMonth() + 1)}-${pad(tm.getDate())}`;
  assert(new RegExp(`${which} 📅 ${TOM}`).test(rd('Todo.md')), 'm moves it to tomorrow: ' + JSON.stringify(rd('Todo.md')));

  if (errors.length) { console.log(errors.join('\n')); process.exitCode = 1; }
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
