const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
(async () => {
  w('Alpha.md', '# Alpha\n\n## Setup steps\ntext\n\n## Results\nThe magic number is 42.\n#project');
  w('Beta.md', 'Nothing magic here? Actually magic appears twice: magic.\n#project #home');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 850 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const mains = () => page.$$eval('.pick .main', p => p.map(x => x.textContent));
  await page.keyboard.press('Control+o'); await sleep(150);
  assert(await page.$eval('.modal input', i => i.value) === '' && (await page.textContent('.lm.on')).includes('Files'), 'Ctrl+O opens on files');
  await page.keyboard.type('alp'); await sleep(100);
  assert((await mains())[0] === 'Alpha', 'finds notes by name');
  await page.keyboard.press('Enter'); await sleep(400);
  assert(await page.evaluate(() => S.cur) === 'Alpha.md', 'and opens them');
  await page.keyboard.press('Control+p'); await sleep(150);
  assert(await page.$eval('.modal input', i => i.value) === '>' && (await page.textContent('.lm.on')).includes('Commands'), 'Ctrl+P opens on commands, with > typed');
  await page.keyboard.type('toggle reading'); await sleep(100);
  assert((await mains())[0].startsWith('Toggle reading'), 'commands are found by name');
  await page.keyboard.press('Backspace'); await page.keyboard.press('Control+a'); await page.keyboard.press('Backspace'); await sleep(100);
  assert((await page.textContent('.lm.on')).includes('Files'), 'deleting the > goes back to files');
  await page.keyboard.type('@res'); await sleep(100);
  assert((await mains())[0].trim() === 'Results', '@ lists the open note’s headings');
  await page.keyboard.press('Enter'); await sleep(300);
  const line = await page.evaluate(() => ed.value.slice(0, ed.selectionStart).split('\n').length);
  assert(line === 6, 'and goes to one (line ' + line + ')');
  await page.keyboard.press('Control+o'); await page.keyboard.type('#pro'); await sleep(100);
  const tags = await page.$$eval('.pick', p => p.map(x => x.textContent));
  assert(tags[0].includes('#project') && tags[0].includes('2 notes'), '# lists tags with their counts: ' + tags[0]);
  await page.keyboard.press('Enter'); await sleep(300);
  assert(await page.$eval('#search-input', i => i.value) === 'tag:project', 'and searches for one');
  await page.keyboard.press('Control+o'); await page.keyboard.type('/magic'); await sleep(150);
  const hits = await page.$$eval('.pick', p => p.map(x => x.querySelector('.sub').textContent));
  assert(hits.filter(h => h === 'Beta').length === 3 && hits.includes('Alpha'), '/ finds text in every note: ' + hits.join(','));
  assert(await page.$eval('.pick mark', m => m.textContent.toLowerCase()) === 'magic', 'with the match marked');
  await page.screenshot({ path: OUT + '/launcher.png' });
  await page.keyboard.press('Enter'); await sleep(400);
  const sel = await page.evaluate(() => [S.cur, ed.value.slice(ed.selectionStart, ed.selectionEnd)]);
  assert(sel[0] === 'Alpha.md' && sel[1] === 'magic', 'and opens the note with it selected');
  await page.keyboard.press('Control+o'); await page.keyboard.type('>'); await sleep(100);
  assert(!(await mains()).some(m => m.startsWith('Create “')), 'no "Create" for commands');
  await page.keyboard.press('Escape');
  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
