const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
(async () => {
  w('Garden plan.md', '#garden\nTomatoes, basil and compost for the raised beds. Water the tomatoes daily. See [[Seeds]].');
  w('Compost.md', '#garden\nKitchen scraps and leaves make compost for the garden beds.');
  w('Tomato varieties.md', 'Cherry tomatoes and beefsteak tomatoes; basil grows well beside them.');
  w('Seeds.md', 'Seed catalogue: tomatoes and basil for the raised beds.');
  w('Rust notes.md', 'Ownership, borrowing and lifetimes in the Rust compiler.');
  w('Groceries.md', 'Milk, bread, eggs.');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 850 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  await page.evaluate(() => openPath('Garden plan.md')); await sleep(300);
  await page.keyboard.press('Control+p'); await page.keyboard.type('show related notes'); await page.keyboard.press('Enter'); await sleep(300);
  const fresh = await page.$$eval('.r-sec:not(.rl-known) .rl-name', r => r.map(x => x.textContent));
  const known = await page.$$eval('.rl-known .rl-name', r => r.map(x => x.textContent));
  assert(fresh.includes('Compost') && fresh.includes('Tomato varieties') && !fresh.includes('Rust notes') && !fresh.includes('Groceries'), 'related notes not linked yet: ' + fresh.join(', '));
  assert(known.join() === 'Seeds', 'the already-linked one is listed apart: ' + known.join());
  assert((await page.textContent('.rl-item[data-path="Compost.md"] .rl-why')).includes('#garden'), 'each says what it shares');
  await page.screenshot({ path: OUT + '/related.png' });
  await page.evaluate(() => { setMode('edit'); ed.setSelectionRange(ed.value.length); ed.focus(); });
  await page.hover('.rl-item[data-path="Compost.md"]'); await page.click('.rl-item[data-path="Compost.md"] .rl-link'); await sleep(300);
  assert((await page.evaluate(() => ed.value)).endsWith('[[Compost]]'), 'Link inserts a link to it');
  await sleep(2200);
  assert(await page.$('.rl-known .rl-item[data-path="Compost.md"]'), 'and it moves to Already linked');
  await page.click('.rl-item[data-path="Tomato varieties.md"]'); await sleep(400);
  assert(await page.evaluate(() => S.cur) === 'Tomato varieties.md', 'clicking one opens it');
  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
