const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
(async () => {
  w('Garden.md', '# Planting\nTomatoes and basil in the raised beds. #home');
  w('Notes/Compost bins.md', 'How to build compost bins for the garden.');
  w('Recipes.md', 'Basil pesto. Receive the café crème.');
  w('Work log.md', '---\nstatus: open\n---\nMeeting about the garden project budget.');
  w('Projects/Cinder.md', 'The notes app. #project/cinder #project/cinder/ui');
  w('Projects/Shed.md', 'Paint it. #project/shed');
  w('Projects/Meta.md', '---\ntags:\n  - project\n  - projects\nalso: [project]\n---\nKeep `#project` and [this](Shed.md#project) and #projects as they are.');
  w('Projects/Inline.md', '---\ntags: [project/shed, diy]\n---\nshed notes');
  w('Todo.md', '- [ ] call the plumber\n- [x] buy seeds\nThe colour of the shed is red.\nIt is blue inside.');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 850 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const search = async q => { await page.evaluate(q => searchFor(q), q); await sleep(250); return page.$$eval('.s-file-name', r => r.map(x => x.childNodes[0].textContent)); };
  let r = await search('garden');
  assert(r[0] === 'Garden' && r.length === 3, 'a title match comes first: ' + r.join(', '));
  r = await search('recieve');
  assert(r.join() === 'Recipes' && (await page.textContent('#search-meta')).includes('receive'), 'typos still find the note, and say what matched');
  assert(await page.$eval('.s-snip mark', m => m.textContent) === 'Receive', 'the snippet marks the word found');
  r = await search('creme');
  assert(r.join() === 'Recipes', 'accents don’t matter');
  r = await search('gard budg');
  assert(r.join() === 'Work log', 'beginnings of words, all of which have to match');
  r = await search('garden -budget');
  assert(!r.includes('Work log') && r.length === 2, 'minus excludes');
  r = await search('garden path:notes');
  assert(r.join() === 'Compost bins', 'operators still work alongside');
  r = await search('[status:open] garden');
  assert(r.join() === 'Work log', 'properties too');
  r = await search('"raised beds"');
  assert(r.join() === 'Garden' && await page.$eval('.s-snip mark', m => m.textContent.toLowerCase()) === 'raised beds', 'exact phrases');
  r = await search('tag:home');
  assert(r.join() === 'Garden', 'tag only');
  r = await search('pesto OR budget');
  assert(r.sort().join() === 'Recipes,Work log', 'OR finds either: ' + r.join());
  r = await search('/colou?r of/');
  assert(r.join() === 'Todo' && await page.$eval('.s-snip mark', m => m.textContent) === 'colour of', '/regex/ matches the text, and the snippet marks it');
  r = await search('line:(shed red)');
  assert(r.join() === 'Todo', 'line:(a b) finds words on one line');
  r = await search('line:(shed blue)');
  assert(!r.length, 'but not words on different lines');
  r = await search('task-todo:plumber');
  assert(r.join() === 'Todo', 'task-todo: searches open tasks');
  r = await search('task-todo:seeds');
  assert(!r.length, 'not done ones');
  r = await search('task-done:');
  assert(r.join() === 'Todo', 'task-done: alone finds notes with done tasks');
  r = await search('content:compost');
  assert(r.join() === 'Compost bins', 'content: looks in the text');
  r = await search('content:recipes');
  assert(!r.length, 'and not the file name');
  // New text is found without a reload.
  await page.evaluate(() => openPath('Recipes.md')); await sleep(300);
  await page.evaluate(() => { setMode('edit'); ed.setSelectionRange(ed.value.length); ed.focus(); });
  await page.keyboard.type(' Zucchini fritters.'); await sleep(1200);
  r = await search('zuchini');
  assert(r.join() === 'Recipes', 'what was just typed is searchable');
  await page.click('.s-snip'); await sleep(300);
  assert(await page.evaluate(() => ed.value.slice(ed.selectionStart, ed.selectionEnd)) === 'Zucchini', 'clicking a snippet selects the match');

  // Nested tags in the tags panel, as in Obsidian.
  await page.evaluate(() => showPanel('tags', true)); await sleep(300);
  const tagRows = () => page.$$eval('#tag-list .tag-row', rs => rs.map(x => x.querySelector('.tag-name').textContent + ' ' + x.querySelector('.n').textContent).join(', '));
  assert((await tagRows()) === '#project 4, #diy 1, #home 1, #projects 1', 'nested tags show under their parent, which counts every note in it: ' + await tagRows());
  await page.click('#tag-list .tag-row[data-tag="project"] [data-tag-toggle]'); await sleep(200);
  assert((await tagRows()) === '#project 4, shed 2, cinder 1, #diy 1, #home 1, #projects 1', 'its › opens it: ' + await tagRows());
  await page.focus('#tag-list .tag-row[data-tag="project/cinder"]'); await page.keyboard.press('ArrowRight'); await sleep(200);
  assert((await tagRows()).startsWith('#project 4, shed 2, cinder 1, ui 1'), '→ opens one from the keyboard: ' + await tagRows());
  await page.keyboard.press('ArrowLeft'); await page.keyboard.press('ArrowLeft'); await sleep(200);
  assert(await page.evaluate(() => document.activeElement.dataset.tag) === 'project', '← closes it, then goes up to its parent');
  await page.click('#tag-list .tag-row[data-tag="project"] .tag-name'); await sleep(300);
  r = await page.$$eval('.s-file-name', r => r.map(x => x.childNodes[0].textContent));
  assert(r.sort().join() === 'Cinder,Inline,Meta,Shed', 'and clicking a parent finds the notes with any tag inside it: ' + r.join());

  // Renaming a tag, as Tag Wrangler does.
  const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
  await page.evaluate(() => showPanel('tags', true)); await sleep(200);
  await page.click('#tag-list .tag-row[data-tag="project"]', { button: 'right' }); await sleep(150);
  await page.click('#menu-root .menu div:has-text("Rename tag")'); await sleep(200);
  await page.fill('#modal-root input', 'work'); await page.keyboard.press('Enter'); await sleep(1500);
  assert(rd('Projects/Cinder.md') === 'The notes app. #work/cinder #work/cinder/ui' && rd('Projects/Shed.md') === 'Paint it. #work/shed', 'Rename tag… changes it in the notes, the tags inside it too');
  assert(rd('Projects/Meta.md') === '---\ntags:\n  - work\n  - projects\nalso: [project]\n---\nKeep `#project` and [this](Shed.md#project) and #projects as they are.', 'and in tags: lists, leaving other tags, other properties, code and links alone: ' + JSON.stringify(rd('Projects/Meta.md')));
  assert(rd('Projects/Inline.md').startsWith('---\ntags: [work/shed, diy]\n'), 'and in a [tags, like, this] property');
  assert((await tagRows()).startsWith('#work 4, shed 2, cinder 1'), 'the tags pane shows it, still open: ' + await tagRows());

  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
