const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
(async () => {
  w('Garden.md', '# Planting\nTomatoes and basil in the raised beds. #home');
  w('Notes/Compost bins.md', 'How to build compost bins for the garden.');
  w('Recipes.md', 'Basil pesto. Receive the café crème.');
  w('Work log.md', '---\nstatus: open\n---\nMeeting about the garden project budget.');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1300, height: 850 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  const search = async q => { await page.evaluate(q => searchFor(q), q); await sleep(250); return page.$$eval('.s-file-name', r => r.map(x => x.childNodes[0].textContent)); };
  let r = await search('garden');
  assert(r[0] === 'Garden' && r.length === 3, 'a title match comes first: ' + r.join(', '));
  r = await search('recieve');
  assert(r.join() === 'Recipes' && (await page.textContent('#search-meta')).includes('receive'), 'typos still find the note, and say what matched');
  assert(await page.$eval('.s-snip mark', m => m.textContent) === 'Receive', 'the snippet marks the word found');
  r = await search('creme');
  assert(r.join() === 'Recipes', 'accents don’t matter');
  r = await search('gard budg');
  assert(r.join() === 'Work log', 'beginnings of words, all of which have to match');
  r = await search('garden -budget');
  assert(!r.includes('Work log') && r.length === 2, 'minus excludes');
  r = await search('garden path:notes');
  assert(r.join() === 'Compost bins', 'operators still work alongside');
  r = await search('[status:open] garden');
  assert(r.join() === 'Work log', 'properties too');
  r = await search('"raised beds"');
  assert(r.join() === 'Garden' && await page.$eval('.s-snip mark', m => m.textContent.toLowerCase()) === 'raised beds', 'exact phrases');
  r = await search('tag:home');
  assert(r.join() === 'Garden', 'tag only');
  // New text is found without a reload.
  await page.evaluate(() => openPath('Recipes.md')); await sleep(300);
  await page.evaluate(() => { setMode('edit'); ed.setSelectionRange(ed.value.length); ed.focus(); });
  await page.keyboard.type(' Zucchini fritters.'); await sleep(1200);
  r = await search('zuchini');
  assert(r.join() === 'Recipes', 'what was just typed is searchable');
  await page.click('.s-snip'); await sleep(300);
  assert(await page.evaluate(() => ed.value.slice(ed.selectionStart, ed.selectionEnd)) === 'Zucchini', 'clicking a snippet selects the match');
  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
