// The sticky layout: a thin window becomes a OneNote-style list of the Inbox's stickies; a sticky
// opens to fill it, with its colour, pin, delete and a formatting bar; notes still open full width;
// widening brings everything back. Stickies can be picked, dragged and deleted from the list.
const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
fs.mkdirSync(OUT, { recursive: true });
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s, t) => { const f = path.join(VAULT, p); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, s); if (t) fs.utimesSync(f, t / 1000, t / 1000); };
const r = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
const has = p => fs.existsSync(path.join(VAULT, p));
(async () => {
  const now = Date.now();
  w('Inbox/Stamps.md', 'Stamps for the letters\n', now - 6e5);
  w('Inbox/Bins.md', 'Bins out on Tuesday\n', now - 5e5);
  w('Inbox/Keys.md', 'Spare keys at the neighbours\n', now - 4e5);
  w('Inbox/Groceries.md', '# Groceries\n\n- [ ] milk\n- [ ] eggs\n', now - 3e5);
  w('Inbox/Call Sam.md', 'Call Sam about the invoice\n', now - 2e5);
  w('Inbox/Garden.md', 'Where the beds go\n', now - 1e5);
  w('Project.md', '# Project\n\nThe big plan.\n');
  const browser = await chromium.launch();
  const page = await (await browser.newContext({ viewport: { width: 1200, height: 900 } })).newPage();
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  await page.evaluate(() => openPath('Project.md')); await sleep(400);
  const shown = sel => page.$$eval(sel, els => els.some(e => e.offsetParent !== null));
  const cards = () => page.$$eval('#view-stickies .sk-card', cs => cs.map(c => c.dataset.path.replace(/^Inbox\//, '').replace(/\.md$/, '')));

  console.log('a thin window');
  await page.setViewportSize({ width: 380, height: 900 }); await sleep(600);
  assert(await page.evaluate(() => document.body.classList.contains('sticky-layout') && S.view === 'stickies'), 'becomes the sticky layout, showing the stickies');
  assert(!(await shown('#ribbon')) && !(await shown('#left')) && !(await shown('#tabbar')), 'with no ribbon, side bars or tabs');
  assert((await cards()).join() === 'Garden,Call Sam,Groceries,Keys,Bins,Stamps', 'newest first, as in New: ' + (await cards()).join());
  assert(await page.evaluate(() => !document.activeElement.closest('.sk-card')), 'no sticky looks selected to begin with');
  await page.keyboard.press('ArrowDown'); await sleep(150);
  assert(await page.evaluate(() => document.activeElement.matches('.sk-card') && document.activeElement.textContent.includes('beds')), '↓ goes to the first sticky');
  await page.screenshot({ path: OUT + '/stickies-list.png' });

  console.log('a new sticky');
  await page.click('[data-sk=new]'); await sleep(600);
  assert(await page.$('#view-stickies .sk-page') && await page.evaluate(() => document.activeElement.closest('.sk-page-body') !== null), '+ opens a new sticky to write in');
  await page.keyboard.type('Buy stamps'); await sleep(1200);
  const made = await page.evaluate(() => $('#view-stickies .sk-page').dataset.path);
  assert(r(made) === 'Buy stamps', 'what’s typed is saved to its file: ' + JSON.stringify(r(made)));
  await page.click('[data-sk=fmt][data-cmd=task-list]'); await sleep(900);
  assert(r(made) === '- [ ] Buy stamps', 'the checklist button makes it a task: ' + JSON.stringify(r(made)));
  await page.keyboard.press('Shift+Control+ArrowLeft'); await page.click('[data-sk=fmt][data-cmd=bold]'); await sleep(900);
  assert(r(made) === '- [ ] Buy **stamps**', 'B bolds the selection: ' + JSON.stringify(r(made)));
  await page.click('[data-sk=color][data-color="4"]'); await sleep(700);
  assert(await page.$eval('#view-stickies .sk-page', p => p.classList.contains('c-4')) && /"color":\s*"4"/.test(r('Inbox/Inbox.canvas')), 'a colour from the header washes it, and is kept on the board');
  await page.click('[data-sk=pin]'); await sleep(700);
  await page.screenshot({ path: OUT + '/stickies-page.png' });
  await page.click('[data-sk=back]'); await sleep(500);
  assert((await cards())[0] === made.replace(/^Inbox\//, '').replace(/\.md$/, ''), '← goes back to the list, the pinned sticky first: ' + (await cards()).join());
  assert(await page.$eval('#view-stickies .sk-sec', h => h.textContent.includes('Pinned')), 'under 📌 Pinned');

  console.log('an empty one goes');
  const before = (await cards()).length;
  await page.keyboard.press('Control+n'); await sleep(600);
  const empty = await page.evaluate(() => $('#view-stickies .sk-page').dataset.path);
  await page.keyboard.press('Escape'); await sleep(600);
  assert(!has(empty) && (await cards()).length === before, 'Ctrl+N makes one, and Esc on it still empty throws it away');

  console.log('search, keys, opening');
  await page.fill('.sk-search', 'invoice'); await sleep(400);
  assert((await cards()).join() === 'Call Sam', 'search finds stickies by their text');
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter'); await sleep(500);
  assert(await page.evaluate(() => $('#view-stickies .sk-page')?.dataset.path) === 'Inbox/Call Sam.md', '↓ and Enter open the one found');
  await page.click('[data-sk=back]'); await sleep(400);
  await page.fill('.sk-search', ''); await sleep(400);

  console.log('leaving a sticky for a note');
  await page.click('#view-stickies .sk-card:has-text("beds")'); await sleep(400);
  await page.keyboard.press('End'); await page.keyboard.type(' by the fence');
  await page.evaluate(() => openPath('Inbox/Garden.md')); await sleep(500);
  assert(await page.evaluate(() => S.view === 'note' && ed.value.includes('by the fence')) && r('Inbox/Garden.md').includes('by the fence'), 'opening the sticky’s own note straight away shows what was just typed in it');
  await page.click('#sk-home'); await sleep(400);
  assert(!(await page.$('#view-stickies .sk-page')) && !(await page.$eval('#view-stickies .sk-list', l => l.classList.contains('covered') || l.inert)), 'and coming back finds the list, not a sticky left open out of sight');

  console.log('a note, and back');
  await page.evaluate(() => openPath('Project.md')); await sleep(500);
  assert(await page.evaluate(() => S.view === 'note') && await shown('#sk-home') && !(await shown('#left')), 'a note opens full width, with ← Stickies');
  const editW = await page.$eval('#editor .cm-content', e => e.getBoundingClientRect().width);
  assert(editW > 300, 'and room to write in: ' + Math.round(editW) + 'px');
  await page.click('#sk-home'); await sleep(400);
  assert(await page.evaluate(() => S.view === 'stickies'), '← Stickies goes home');

  console.log('picking and deleting, without opening');
  const card = t => `#view-stickies .sk-card:has-text("${t}")`;
  const count = () => page.$eval('#view-stickies .sk-head', h => h.textContent.replace(/\s+/g, ' ').trim());
  const picked = () => page.$$eval('#view-stickies .sk-card.sel', cs => cs.map(c => c.dataset.path.replace(/^Inbox\//, '').replace(/\.md$/, '')).join());
  await page.hover(card('neighbours')); await page.click(card('neighbours') + ' .sk-check'); await sleep(200);
  assert(await picked() === 'Keys' && (await count()).includes('1 selected'), 'the ✓ on a sticky picks it, and the header says so');
  await page.click(card('letters'), { modifiers: ['Shift'] }); await sleep(200);
  assert(await picked() === 'Keys,Bins,Stamps', 'Shift-click picks the run: ' + await picked());
  await page.click(card('Tuesday')); await sleep(200);
  assert(await picked() === 'Keys,Stamps' && !(await page.$('#view-stickies .sk-page')), 'while picking, a click picks or unpicks, not opens');
  await page.click('[data-sk=sel-delete]'); await sleep(700);
  assert(!has('Inbox/Keys.md') && !has('Inbox/Stamps.md') && has('Inbox/Bins.md') && !(await page.$('.confirm')), 'Delete in the bar deletes the picked ones, without a dialog to answer');
  assert(!(await picked()) && !(await page.$('.sk-selbar')) && !(await cards()).includes('Keys'), 'and the list is back to normal');
  assert(await page.$eval('.toast.has-action', t => t.textContent.includes('2 stickies deleted')), 'a note says so, with Undo');
  await page.click('.toast button:has-text("Undo")'); await sleep(1200);
  assert(has('Inbox/Keys.md') && r('Inbox/Stamps.md').includes('letters') && (await cards()).join().endsWith('Keys,Bins,Stamps'), 'Undo puts them back where they were: ' + (await cards()).join());
  await page.click(card('Tuesday'), { button: 'right' }); await sleep(200);
  await page.click('#menu-root .menu div:has-text("Delete")'); await sleep(700);
  assert(!has('Inbox/Bins.md') && !(await cards()).includes('Bins'), 'right-click → Delete deletes one');
  await page.keyboard.press('Control+z'); await sleep(1200);
  assert(has('Inbox/Bins.md') && (await cards()).join().endsWith('Keys,Bins,Stamps'), 'and Ctrl+Z brings it back');
  await page.hover(card('Buy')); await page.click(card('Buy') + ' [data-sk=card-delete]'); await sleep(700);
  assert(!has(made), 'the 🗑 on a sticky deletes it');
  await page.keyboard.press('Control+z'); await sleep(1500);
  assert((await cards())[0] === made.replace(/^Inbox\//, '').replace(/\.md$/, '') && await page.$eval(card('Buy'), c => c.classList.contains('c-4')), 'and one put back is pinned again, in its colour');
  await page.focus(card('neighbours')); await page.keyboard.press('Delete'); await sleep(700);
  await page.focus(card('letters')); await page.keyboard.press('Delete'); await sleep(700);
  await page.focus(card('Tuesday')); await page.keyboard.press('Delete'); await sleep(700);
  assert(!has('Inbox/Keys.md') && !has('Inbox/Stamps.md') && !has('Inbox/Bins.md'), 'Delete on a sticky deletes it');
  await page.focus(card('beds')); await page.keyboard.press('Control+a'); await sleep(200);
  assert((await picked()).split(',').length === (await cards()).length, 'Ctrl+A picks them all');
  await page.keyboard.press('Escape'); await sleep(200);
  assert(!(await picked()) && !(await page.$('.sk-selbar')), 'and Esc lets them go');

  console.log('dragging');
  const box = async t => (await page.$(card(t))).boundingBox();
  const drag = async (from, x, y) => {
    const a = await box(from);
    await page.mouse.move(a.x + 20, a.y + 20); await page.mouse.down();
    await page.mouse.move(a.x + 24, a.y + 30, { steps: 3 }); await sleep(100);
    await page.mouse.move(x, y, { steps: 8 });
    await page.mouse.move(x + 2, y + 2); await sleep(400); // (the last drag events arrive late)
  };
  const sam = await box('invoice');
  await drag('milk', sam.x + 40, sam.y + 6);
  assert(await page.$eval('#view-stickies .sk-list', l => l.classList.contains('dragging')) && await shown('#view-stickies .sk-trash'), 'a drag lifts the sticky, and shows a bin to drop it on');
  assert(await page.$eval('#view-stickies .sk-ph', g => g.nextElementSibling?.textContent.includes('invoice')), 'the others make room where it would land');
  await page.mouse.up(); await sleep(800);
  const order = (await cards()).join();
  assert(order.indexOf('Groceries') < order.indexOf('Call Sam'), 'dropped above another, it moves there: ' + order);
  assert(/Groceries/.test(r('Inbox/Inbox.canvas')), 'and the board keeps the order');
  await drag('milk', 190, 860);
  assert(await page.$eval('#view-stickies .sk-trash', t => t.classList.contains('over')), 'over the bin, it lights up');
  await page.mouse.up(); await sleep(900);
  assert(!has('Inbox/Groceries.md') && !(await cards()).includes('Groceries'), 'dropped on the bin, it’s deleted');
  await page.screenshot({ path: OUT + '/stickies-picked.png' });

  console.log('widening');
  await page.click('.sk-card:has-text("beds")'); await sleep(400);
  await page.setViewportSize({ width: 1200, height: 900 }); await sleep(800);
  assert(await page.evaluate(() => !document.body.classList.contains('sticky-layout') && S.view === 'note' && S.cur === 'Project.md'), 'brings the full layout back, and what was open before');
  assert(await shown('#ribbon') && await shown('#left'), 'with the ribbon and side bar');
  await page.evaluate(() => { cfg.stickyLayout = false; saveCfg(); });
  await page.setViewportSize({ width: 380, height: 900 }); await sleep(600);
  assert(await page.evaluate(() => !document.body.classList.contains('sticky-layout') && S.view === 'note'), 'with the setting off, a thin window keeps the full layout');
  assert(!(await shown('#left')), 'though the side bar still folds away, leaving the note room');
  await page.evaluate(() => { cfg.stickyLayout = true; saveCfg(); });

  assert(!errors.length, 'no page errors: ' + errors.join(' | '));
  await browser.close();
})().catch(e => { console.error(e.message); process.exit(1); });
