const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
const pad = n => String(n).padStart(2, '0');
const day = k => { const d = new Date(); d.setDate(d.getDate() + k); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; };
(async () => {
  const T0 = day(0), Y = day(-1), TM = day(1);
  w('Projects/Launch.md', `# Launch\n- [ ] Write press release 📅 ${Y} ⏫ #work\n- [ ] Book venue 📅 ${T0}\n- [ ] Water plants 🔁 every week 📅 ${T0} #home\n- [ ] Someday idea\n- [x] Old thing ✅ ${Y}\n`);
  w('Dashboard.md', '# Dashboard\n\n```tasks\nnot done\ndue on or before today\nsort by priority\n```\n\n- [ ] local task\n');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  const errors = []; global.PAGE = page; global.ERRS = errors;
  page.on('pageerror', e => errors.push('pageerror: ' + e.message + '\n' + e.stack));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(900);
  assert((await page.textContent('[data-cmd=tasks] .rb-badge')) === '3', 'ribbon badge counts overdue + today (3)');
  await page.keyboard.press('Control+Shift+T'); await sleep(400);
  const secs = () => page.$$eval('.tk-section h3', h => h.map(x => x.textContent.trim()));
  const list = id => page.click(`.tk-li[data-list="${id}"]`).then(() => sleep(200));
  const navN = id => page.$eval(`.tk-li[data-list="${id}"]`, b => b.querySelector('b')?.textContent || '0');
  assert((await secs()).join('|') === 'Overdue 1|Today 2', 'Tasks opens on Today: ' + (await secs()).join(' | '));
  assert(await navN('today') === '3' && await navN('anytime') === '2' && await navN('all') === '5', 'the side bar counts each list');
  assert(await page.$('.tk-li[data-list="note:Projects/Launch.md"]') && await page.$('.tk-li[data-list="tag:work"]'), 'and lists notes and tags with open tasks');
  assert(await page.evaluate(() => document.activeElement.classList.contains('tk-add')), 'quick add input focused');
  console.log('quick add');
  await page.keyboard.type('Buy milk tomorrow !high #errand');
  const pv = await page.textContent('.tk-preview');
  assert(pv.includes('Buy milk #errand') && pv.includes('Tomorrow') && pv.includes('High'), 'live preview understands it: ' + pv);
  await page.keyboard.press('Enter'); await sleep(900);
  assert(rd(`Daily/${T0}.md`) === `- [ ] Buy milk #errand ⏫ 📅 ${TM}\n`, 'written to today\'s daily note in Tasks format');
  assert(await page.evaluate(() => document.activeElement.classList.contains('tk-add')), 'input stays focused for the next task');
  await page.keyboard.type('Call mum'); await page.keyboard.press('Enter'); await sleep(900);
  assert(rd(`Daily/${T0}.md`).endsWith(`- [ ] Call mum 📅 ${T0}\n`), 'in Today, a task without a date is for today');
  await list('upcoming');
  assert((await secs()).includes('Tomorrow 1'), 'Upcoming shows tomorrow’s task: ' + (await secs()).join(' | '));

  console.log('complete with undo, recur');
  await list('today');
  await page.click('.tk-row:has-text("Water plants") .tk-check'); await sleep(1400);
  let f = rd('Projects/Launch.md');
  assert(f.includes(`- [ ] Water plants 🔁 every week 📅 ${day(7)} #home\n- [x] Water plants 🔁 every week 📅 ${T0} #home ✅ ${T0}\n`), 'recurring task completed with ✅ and next occurrence added above');
  await page.click('.toast button:has-text("Undo")'); await sleep(1200);
  assert(rd('Projects/Launch.md').includes(`- [ ] Water plants 🔁 every week 📅 ${T0} #home\n- [ ] Someday idea`), 'Undo puts it back as it was: ' + JSON.stringify(rd('Projects/Launch.md')));

  console.log('reschedule, details, edit, delete');
  await list('anytime');
  await page.hover('.tk-row:has-text("Someday idea")');
  await page.click('.tk-row:has-text("Someday idea") [data-act=today]'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Someday idea 📅 ${T0}\n`), 'the Today button schedules it');
  await list('all');
  await page.setViewportSize({ width: 1400, height: 1500 }); await sleep(200);
  await page.dragAndDrop('.tk-row:has-text("Book venue")', '.tk-section[data-date=""]'); await sleep(900);
  assert(rd('Projects/Launch.md').includes('- [ ] Book venue\n'), 'dragging to "No date" removes the date');
  await page.dragAndDrop('.tk-row:has-text("Book venue")', `.tk-section[data-date="${TM}"]`); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Book venue 📅 ${TM}\n`), 'dragging onto Tomorrow reschedules');
  await page.setViewportSize({ width: 1400, height: 900 }); await sleep(200);
  const details = async () => { await page.hover('.tk-row:has-text("Book venue")'); await page.click('.tk-row:has-text("Book venue") [data-act=more]'); await sleep(150); };
  await details();
  await page.screenshot({ path: OUT + '/tk-details.png' });
  await page.click('.tk-pop [data-prio=highest]'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Book venue 📅 ${TM} 🔺\n`), 'priority from the details popover');
  await details(); await page.click('.tk-pop [data-recur="every week"]'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Book venue 📅 ${TM} 🔺 🔁 every week\n`), 'repeat from the details popover');
  await details(); await page.fill('.tk-pop .tk-recur-in', 'mon, thu'); await page.press('.tk-pop .tk-recur-in', 'Enter'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`🔁 every mon, thu`), 'a typed repeat rule');
  await details(); await page.click('.tk-pop [data-when="' + day(0) + '"]'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Book venue 📅 ${T0}`), 'a date from the details popover');
  await page.click('.tk-row:has-text("Book venue") .tk-text'); await sleep(100);
  await page.fill('.tk-edit', 'Book the big venue'); await page.press('.tk-edit', 'Enter'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [ ] Book the big venue 📅 ${T0} 🔺 🔁 every mon, thu\n`), 'clicking the text edits it, keeping dates and flags: ' + rd('Projects/Launch.md').split('\n')[3]);
  await page.focus('.tk-row:has-text("Call mum")'); await page.keyboard.press('Delete'); await sleep(900);
  assert(!rd(`Daily/${T0}.md`).includes('Call mum'), 'Delete removes the task’s line');
  await page.click('.toast button:has-text("Undo")'); await sleep(900);
  assert(rd(`Daily/${T0}.md`).includes(`- [ ] Call mum 📅 ${T0}`), 'and Undo brings it back');
  await page.fill('.tk-search', 'venue'); await sleep(200);
  assert(await page.$$eval('.tk-row', r => r.length) === 1, 'filter narrows the list');
  await page.fill('.tk-search', ''); await sleep(100);

  console.log('tag and note lists, target note');
  await list('tag:errand');
  assert(await page.$$eval('.tk-row', r => r.map(x => x.querySelector('.tk-text').textContent)).then(t => t.length === 1 && t[0].includes('Buy milk')), 'a tag’s list');
  await page.click('.tk-add'); await page.keyboard.type('Get stamps'); await page.keyboard.press('Enter'); await sleep(900);
  assert(rd(`Daily/${T0}.md`).includes('- [ ] Get stamps #errand'), 'adding in a tag’s list tags the task');
  await list('note:Projects/Launch.md');
  assert(await page.$eval('.tk-group .on', b => b.textContent) === 'Heading', 'a note’s list is grouped by heading');
  await page.click('.tk-add'); await page.keyboard.type('Print flyers'); await page.keyboard.press('Enter'); await sleep(900);
  assert(rd('Projects/Launch.md').endsWith('- [ ] Print flyers\n'), 'adding in a note’s list adds to that note');
  await list('today');
  await page.click('.tk-target'); await sleep(200); await page.keyboard.type('Dashboard'); await page.keyboard.press('Enter'); await sleep(200);
  assert((await page.textContent('.tk-target')).includes('Dashboard'), 'the target button picks another note');
  await page.keyboard.type('Check the numbers'); await page.keyboard.press('Enter'); await sleep(900);
  assert(rd('Dashboard.md').includes(`- [ ] Check the numbers 📅 ${T0}`), 'and new tasks go there');
  await page.click('.tk-group [data-group=note]'); await sleep(200);
  assert((await secs()).some(s => s.startsWith('Launch')), 'group by note');
  await page.click('.tk-group [data-group=date]'); await sleep(200);
  await list('logbook');
  assert(await page.$$eval('.tk-row.done', r => r.length) >= 1, 'the Logbook lists done tasks');
  await list('today');
  await page.screenshot({ path: OUT + '/60-tasks.png' });
  console.log('jump to source; editor checkbox; ```tasks blocks');
  await page.click('.tk-row:has-text("Write press release") .tk-src'); await sleep(600);
  const sel = await page.evaluate(() => [S.cur, ed.value.slice(ed.selectionStart, ed.selectionEnd)]);
  assert(sel[0] === 'Projects/Launch.md' && sel[1].startsWith('- [ ] Write press release'), 'source link opens the note at the task');
  await page.evaluate(() => { const i = ed.value.indexOf('- [ ] Write press release'); ed.setSelectionRange(i + 8, i + 8); });
  await page.keyboard.press('Control+Enter'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [x] Write press release 📅 ${Y} ⏫ #work ✅ ${T0}`), 'Ctrl+Enter in the editor ticks with a done date');
  await page.keyboard.press('Control+o'); await page.keyboard.type('Dashboard'); await page.keyboard.press('Enter'); await sleep(900);
  let q = await page.$$eval('.cm-codeblock-widget .tk-row .tk-text', r => r.map(x => x.textContent));
  assert(q.includes('Someday idea') && !q.some(x => x.includes('Buy milk')), '```tasks block shows open tasks due by today: ' + q.join('|'));
  await page.click('.cm-codeblock-widget .tk-row:has-text("Someday idea") .tk-check'); await sleep(900);
  assert(rd('Projects/Launch.md').includes(`- [x] Someday idea 📅 ${T0} ✅ ${T0}`), 'ticking in a query block updates the source note');
  await page.click('.cm-line >> text=local task'); 
  const cb = page.locator('.cm-line:has-text("local task") .cm-task-cb');
  await page.keyboard.press('Control+End'); await sleep(200);
  await cb.click(); await sleep(900);
  assert(rd('Dashboard.md').includes(`- [x] local task ✅ ${T0}`), 'clicking a checkbox in live preview adds the done date');
  await page.keyboard.press('Control+e'); await sleep(500);
  assert(await page.$$eval('#preview .tasks-embed .tk-row', r => r.length) >= 1, 'reading view renders the query');
  await page.screenshot({ path: OUT + '/61-dashboard.png' });
  console.log('quick add from the palette');
  await page.keyboard.press('Control+p'); await page.keyboard.type('Add task'); await page.keyboard.press('Enter'); await sleep(200);
  await page.keyboard.type('Plan retro next friday every 2 weeks'); await sleep(100);
  assert((await page.textContent('.modal .tk-preview')).includes('repeats every 2 weeks'), 'palette quick add previews');
  await page.keyboard.press('Enter'); await sleep(900);
  assert(/- \[ \] Plan retro 🔁 every 2 weeks 📅 \d{4}-\d\d-\d\d\n$/.test(rd(`Daily/${T0}.md`)), 'palette quick add appends to the inbox');
  console.log('rollover');
  w('Misc.md', `- [ ] Old overdue 📅 ${day(-3)}\n- [ ] Also late 📅 ${day(-1)}\n`); await sleep(2600);
  await page.keyboard.press('Control+Shift+T'); await sleep(400);
  await page.click('[data-roll]'); await sleep(1200);
  assert(!(await page.$('.tk-section.tk-danger')) && rd('Misc.md') === `- [ ] Old overdue 📅 ${T0}\n- [ ] Also late 📅 ${T0}\n`, 'Move them all to today clears Overdue');
  console.log('ERRORS:', errors.join('\n') || 'none');
  assert(!errors.length, 'no page errors');
  await browser.close();
})().catch(async e => { console.error(e.message); try { await global.PAGE.screenshot({ path: OUT + '/fail.png' }); } catch {} console.log('ERRORS:', (global.ERRS || []).join('\n')); process.exit(1); });
