const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault', OUT = SP + '/shots';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
const w = (p, s) => { fs.mkdirSync(path.dirname(path.join(VAULT, p)), { recursive: true }); fs.writeFileSync(path.join(VAULT, p), s); };
const rd = p => fs.readFileSync(path.join(VAULT, p), 'utf8');
(async () => {
  w('Templates/Meeting.md', '---\ntype: meeting\n---\n# <% tp.file.title %>\nDate: <% tp.date.now("YYYY-MM-DD") %>\n<%* const who = await tp.system.prompt("Who is attending?") -%>\nAttendees: <% who %>\n<%* await tp.file.rename("Meeting with " + who) -%>\n## Notes\n<% tp.file.cursor() %>\n');
  w('Templates/Quote.md', '> <% tp.file.selection() %>\n> — <% tp.frontmatter.author ?? "unknown" %>');
  w('Templates/Daily.md', '# <% tp.date.now("dddd, MMMM Do") %>\n<%* if (tp.date.now("d") === "0") { %>Sunday!<%* } else { %>Weekday<%* } %>\n- [ ] <% tp.file.cursor() %>');
  w('Templates/Broken.md', '<% tp.nope.x() %>');
  w('Book.md', '---\nauthor: Ursula\n---\nA wizard of earthsea');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  const errors = []; global.PAGE = page;
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  await page.goto('http://127.0.0.1:43199/'); await sleep(800);
  const today = await page.evaluate(() => CinderTemplater.formatDate(new Date(), 'YYYY-MM-DD'));
  console.log('folder template with prompt, rename and cursor');
  await page.evaluate(() => openSettings('templates'));
  await page.fill('textarea[name=folderTemplates]', 'Meetings: Templates/Meeting'); await page.keyboard.press('Tab');
  await page.click('.st-page[data-page=daily]');
  await page.fill('input[name=dailyTemplate]', 'Templates/Daily'); await page.keyboard.press('Tab');
  await page.click('.st [data-x]');
  const p = page.evaluate(() => newNote('Meetings'));
  await page.waitForSelector('.modal textarea, .modal input[name=v]'); await sleep(100);
  assert((await page.textContent('.modal label')).includes('Who is attending?'), 'tp.system.prompt asks the question');
  await page.keyboard.type('Ada'); await page.keyboard.press('Enter');
  await p; await sleep(1200);
  assert(fs.existsSync(path.join(VAULT, 'Meetings/Meeting with Ada.md')), 'tp.file.rename renamed the new note');
  const m = rd('Meetings/Meeting with Ada.md');
  assert(m.startsWith('---\ntype: meeting\n---\n# Untitled\n'), 'frontmatter kept; title rendered before the rename (as in Templater)');
  assert(m.includes(`Date: ${today}\nAttendees: Ada\n## Notes\n`), 'date, prompt answer and whitespace control rendered');
  assert(!m.includes('<%'), 'no template tags left');
  const sel = await page.evaluate(() => [S.cur, ed.selectionStart, ed.value.length, ed.value.slice(ed.selectionStart - 9, ed.selectionStart)]);
  assert(sel[0] === 'Meetings/Meeting with Ada.md' && sel[3] === '## Notes\n', 'cursor placed at tp.file.cursor(): ' + JSON.stringify(sel));
  console.log('insert template with selection & frontmatter');
  await page.keyboard.press('Control+o'); await page.keyboard.type('Book'); await page.keyboard.press('Enter'); await sleep(400);
  await page.evaluate(() => { if (S.mode !== 'edit') setMode('edit'); const i = ed.value.indexOf('A wizard'); ed.setSelectionRange(i, ed.value.length); });
  await page.keyboard.press('Control+p'); await page.keyboard.type('Insert template'); await page.keyboard.press('Enter'); await sleep(150);
  await page.keyboard.type('Quote'); await page.keyboard.press('Enter'); await sleep(1200);
  assert(rd('Book.md').endsWith('> A wizard of earthsea\n> — Ursula'), 'selection and tp.frontmatter used: ' + JSON.stringify(rd('Book.md').slice(-40)));
  console.log('new note from template, replace in note, daily note');
  await page.keyboard.press('Control+p'); await page.keyboard.type('new note from template'); await page.keyboard.press('Enter'); await sleep(150);
  await page.keyboard.type('Quote'); await page.keyboard.press('Enter'); await sleep(1200);
  assert(rd('Untitled.md') === '> \n> — unknown', 'new note from template: ' + JSON.stringify(rd('Untitled.md')));
  await page.evaluate(() => { ed.insert(0, ed.value.length, 'Made <% tp.date.now("YYYY") %> in <% tp.file.folder(true) || "root" %>'); });
  await page.keyboard.press('Control+p'); await page.keyboard.type('Replace template commands'); await page.keyboard.press('Enter'); await sleep(1200);
  assert(rd('Untitled.md') === `Made ${today.slice(0, 4)} in root`, 'replace templates in the current note');
  await page.click('[data-cmd=daily]'); await sleep(1200);
  const daily = rd(`Daily/${today}.md`);
  assert(/^# \w+day, \w+ \d+(st|nd|rd|th)\n(Sunday!|Weekday)\n- \[ \] $/.test(daily), 'daily note from a Templater template: ' + JSON.stringify(daily));
  assert(await page.evaluate(() => ed.selectionStart === ed.value.length), 'daily cursor at tp.file.cursor()');
  console.log('errors are reported, nothing inserted');
  await page.keyboard.press('Control+o'); await page.keyboard.type('Book'); await page.keyboard.press('Enter'); await sleep(400);
  const before = rd('Book.md');
  await page.keyboard.press('Control+p'); await page.keyboard.type('Insert template'); await page.keyboard.press('Enter'); await sleep(150);
  await page.keyboard.type('Broken'); await page.keyboard.press('Enter'); await sleep(300);
  const t = await page.textContent('.toast').catch(() => '');
  assert(/^Template error in Broken: /.test(t), 'error toast: ' + t);
  await sleep(1000);
  assert(rd('Book.md') === before, 'broken template inserts nothing');
  console.log('ERRORS:', errors.join('\n') || 'none');
  await browser.close();
})().catch(async e => { console.error(e.message); try { await global.PAGE.screenshot({ path: OUT + '/fail.png' }); } catch {} process.exit(1); });
