const { chromium } = require('playwright-core');
const fs = require('fs'), path = require('path');
const SP = process.env.SP, VAULT = SP + '/vault';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const assert = (c, m) => { if (!c) throw new Error('ASSERT: ' + m); console.log('  ✓', m); };
(async () => {
  fs.writeFileSync(path.join(VAULT, 'A.md'), 'one');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
  const errors = [];
  page.on('pageerror', e => errors.push('pageerror: ' + e.message));
  let lists = 0;
  page.on('request', r => { if (r.url().includes('/api/list')) lists++; });
  await page.goto('http://127.0.0.1:43199/'); await sleep(1500);
  await page.evaluate(() => openPath('A.md')); await sleep(300);
  const before = lists;
  await sleep(4500);
  assert(lists - before <= 1, `with nothing changing, the page doesn't keep asking (${lists - before} lists in 4.5 s)`);
  const t0 = Date.now();
  fs.writeFileSync(path.join(VAULT, 'A.md'), 'two');
  await page.waitForFunction(() => ed.value === 'two', null, { timeout: 5000 });
  const dt = Date.now() - t0;
  assert(dt < 1200, `a change on disk shows almost at once (${dt} ms)`);
  fs.writeFileSync(path.join(VAULT, 'New.md'), 'new');
  await page.waitForSelector('#tree .t-row[data-path="New.md"]', { timeout: 3000 });
  assert(true, 'a new file appears in the tree');
  fs.mkdirSync(path.join(VAULT, 'Deep/er'), { recursive: true });
  fs.writeFileSync(path.join(VAULT, 'Deep/er/Z.md'), 'z');
  await page.waitForFunction(() => S.files.has('Deep/er/Z.md'), null, { timeout: 3000 });
  assert(true, 'changes in new subfolders are seen too');
  assert(errors.length === 0, 'no page errors ' + errors.join('; '));
  await browser.close();
})().catch(e => { console.log(e.message); process.exit(1); });
