#!/usr/bin/env python3
"""Writes THIRD-PARTY-LICENSES.md: every Rust crate compiled into Cinder (on any platform) with its
license and the license texts it ships, for handing out with the app. The web libraries in
ui/vendor carry their own license files (listed in the README).

Run it after changing Cargo dependencies:  python3 packaging/third-party-licenses.py
"""
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
LICENSE_FILE = re.compile(r'^(licen[cs]e|copying|notice|unlicense)([-._].*)?$', re.I)

meta = json.loads(subprocess.run(['cargo', 'metadata', '--format-version', '1', '--locked'], cwd=ROOT,
                                 check=True, capture_output=True, text=True).stdout)
members = set(meta['workspace_members'])
packages = {p['id']: p for p in meta['packages']}
nodes = {n['id']: n for n in meta['resolve']['nodes']}

# What's built into Cinder: its dependencies and theirs, including build scripts, not dev-only ones.
seen, stack = set(), list(members)
while stack:
    pid = stack.pop()
    if pid in seen:
        continue
    seen.add(pid)
    for d in nodes[pid]['deps']:
        if any(k['kind'] != 'dev' for k in d['dep_kinds']):
            stack.append(d['pkg'])
crates = sorted((packages[i] for i in seen - members), key=lambda p: (p['name'].lower(), p['version']))

texts = {}      # license text (whitespace-normalised) -> (the text, crates that ship it)
bare = []       # crates that ship no license file
for p in crates:
    folder = pathlib.Path(p['manifest_path']).parent
    files = [f for f in sorted(folder.iterdir()) if f.is_file() and LICENSE_FILE.match(f.name)]
    if p.get('license_file'):
        extra = folder / p['license_file']
        if extra.is_file() and extra not in files:
            files.append(extra)
    label = f"{p['name']} {p['version']}"
    if not files:
        bare.append(p)
    for f in files:
        text = f.read_text(encoding='utf-8', errors='replace').strip()
        key = re.sub(r'\s+', ' ', text)  # the same text laid out differently is the same text
        texts.setdefault(key, (text, []))[1].append(label)

out = [
    '# Third-party licenses',
    '',
    'Cinder is licensed under MIT OR Apache-2.0 (see LICENSE-MIT and LICENSE-APACHE). The Rust crates '
    'compiled into it are listed below, with the license texts they ship. Generated by '
    '`packaging/third-party-licenses.py` from `Cargo.lock`; the list covers every platform. The web '
    'libraries and fonts in `ui/vendor` carry their own license files there.',
    '',
    '## Crates',
    '',
    '| Crate | Version | License |',
    '|---|---|---|',
]
out += [f"| {p['name']} | {p['version']} | {p.get('license') or 'see its license file'} |" for p in crates]
if bare:
    out += ['', 'These ship no license file of their own; their license is the standard text named above: '
            + ', '.join(f"{p['name']} {p['version']} ({p.get('license')})" for p in bare) + '.']
out += ['', '## License texts', '']
for n, (text, users) in enumerate(sorted(texts.values(), key=lambda tu: tu[1][0].lower()), 1):
    fence = '~~~~' if '```' in text else '```'
    out += [f'### {n}. Used by {", ".join(users)}', '', fence + 'text', text, fence, '']

(ROOT / 'THIRD-PARTY-LICENSES.md').write_text('\n'.join(out), encoding='utf-8')
print(f'{len(crates)} crates, {len(texts)} distinct license texts, {len(bare)} without a license file')
